# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: dev
  displayName: Dev envrionment
  jobs:
  - job: Job01
    displayName: Job 01 runs on ubuntu Linux
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo $(System.ArtifactsDirectory)
      displayName: 'Run a multi-line script'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          Write-Host "Hello World"
          Write-Host ${System.ArtifactsDirectory}
          Get-ChildItem -Path ${System.ArtifactsDirectory}
  - job: Job02
    variables:
      serviceConnectionDEV: 'azureSubscription'
    dependsOn: Job01
    displayName: Job 02 to test depedency
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo Hello, Job 02 $(serviceConnectionDEV)
  - deployment: Job03
    displayName: deploy azure resource group
    environment: 'dev'
    dependsOn: Job02
    variables:
      resourceManagerConnection: 'Microsoft Azure Internal Consumption(f2de2f04-15eb-4eaa-ae36-29f88195f2f2)'
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                # Write your PowerShell commands here.
                Write-Host "Hello World"
                Write-Host ${System.ArtifactsDirectory}
                Get-ChildItem -Path ${System.ArtifactsDirectory}
                Write-Host $(System.DefaultWorkingDirectory)
                Get-ChildItem -Path $(System.DefaultWorkingDirectory)

          - task: AzureResourceGroupDeployment@2
            displayName: 'Azure Deployment:Create Or Update Resource Group action on TaskList'
            inputs:
              azureSubscription: 'Microsoft Azure Internal Consumption(f2de2f04-15eb-4eaa-ae36-29f88195f2f2)'
              resourceGroupName: TaskList
              location: 'East US 2'
              csmFile: '$(System.DefaultWorkingDirectory)/_rahulvmarathe.yamlcicd/drop/appservice.json'