# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: dev
  displayName: Dev envrionment
  jobs:
  - job: Job01
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
  - deployment: Job02
    displayName: Deploy azure resource group
    environment: 'dev'
    dependsOn: 'job01'
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: steps.json
            parameters:
              parameterConnection01: 'AzureDevConnection'
