# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

extends:
  template: 'https://github.com/rahulvmarathe/yamlcicdcore/blob/master/basetemplate.json'
  parameters:
    buildSteps: 'buildsteps.json'
    steps: 'steps.json'
    
