# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: dev
  displayName: Dev envrionment
  jobs:
  - deployment: Job01
    displayName: deploy azure resource group
    environment: 'dev'
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: steps.json
            parameters:
              parameterConnection01: 'AzureDevConnection'
